name: 'Callable CI'

on:
  workflow_call:
    inputs:
      run_lint:
        description: 'Run lint checks'
        type: boolean
        required: true
      run_tests:
        description: 'Run tests'
        type: boolean
        required: true
      run_build:
        description: 'Run build'
        type: boolean
        required: true
    secrets:
      LINEAR_API_KEY_E2E:
        description: Linear API key for E2E tests
        required: true
      LINEAR_TEST_ISSUE_ID:
        description: Linear test issue ID for E2E tests
        required: true
      LINEAR_TEST_TEAM:
        description: Linear test team for E2E tests
        required: true

jobs:
  build:
    if: inputs.run_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Build package
        run: pnpm run build

  lint:
    if: inputs.run_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install

      - name: Run lint
        run: pnpm run lint

      - name: Run typecheck
        run: pnpm run typecheck

  test-e2e:
    if: inputs.run_tests
    runs-on: ubuntu-latest
    env:
      LINEAR_API_KEY_E2E: ${{ secrets.LINEAR_API_KEY_E2E }}
      LINEAR_TEST_ISSUE_ID: ${{ secrets.LINEAR_TEST_ISSUE_ID }}
      LINEAR_TEST_TEAM: ${{ secrets.LINEAR_TEST_TEAM }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
      - run: pnpm run test:e2e
