name: 'PR Validation'

# NOTE: if there is conflict with the main branch, the PR will not trigger the GITHUB ACTIONS
# REF: https://stackoverflow.com/questions/61989951/github-action-workflow-not-running/70614176#70614176

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  pr_ci:
    name: 'PR CI'
    uses: ./.github/workflows/callable-ci.yml
    with:
      run_lint: true
      run_build: true
      run_tests: ${{ contains(github.event.pull_request.labels.*.name, 'run_tests') }}
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      LINEAR_API_KEY_E2E: ${{ secrets.LINEAR_API_KEY_E2E }}
      LINEAR_TEST_ISSUE_ID: ${{ secrets.LINEAR_TEST_ISSUE_ID }}

