name: 'PR Validation'

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_ci:
    name: 'PR CI'
    uses: ./.github/workflows/callable-ci.yml
    with:
      run_lint: true
      run_tests: ${{ contains(github.event.pull_request.labels.*.name, 'run_tests') }}
      run_build: true
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      LINEAR_API_KEY_E2E: ${{ secrets.LINEAR_API_KEY_E2E }}
      LINEAR_TEST_ISSUE_ID: ${{ secrets.LINEAR_TEST_ISSUE_ID }}

