name: 'Main Branch & Release'

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: write
  id-token: write

jobs:
  push_to_main_ci:
    name: 'Main CI'
    uses: ./.github/workflows/callable-ci.yml
    with:
      run_lint: true
      run_tests: true
      run_build: true
    secrets: inherit

  release:
    name: 'Release Package'
    needs: [push_to_main_ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-install
      - run: echo "HUSKY=0" >> $GITHUB_ENV
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
